exclude: '.terraform'
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.3.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=5000]
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: pretty-format-json
    args: [--autofix, --indent=2, --no-ensure-ascii]
  - id: trailing-whitespace

- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  sha: v1.17.0
  hooks:
  - id: terraform_fmt

- repo: local
  hooks:
  - id: test
